name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/finall_lab:latest
    
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ~/finall_lab
          cd ~/finall_lab
          
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml -o docker-compose.yml
          
          sed -i 's/build: \./image: ${{ secrets.DOCKER_HUB_USERNAME }}\/finall_lab:latest/' docker-compose.yml
          
          max_retries=3
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            docker-compose down || true
            docker-compose pull && break
            retry_count=$((retry_count+1))
            echo ">>> Pull failed, retrying ($retry_count/$max_retries)..."
            sleep 5
          done
          docker-compose up -d
          docker-compose ps